### PR TITLE
Add support for the log crate

### PR DESCRIPTION
**Pull request by robbert-vdh**
This is useful when the log output is going somewhere other than STDERR. I've added this for a fork to use with NIH-plug, but I thought others might find it useful as well. This will sadly still print the original allocation failure message from `std::alloc::handle_alloc_error` in addition to the log output as that handler function must be called here.

I didn't know what the preferred way to integrate this into an example or test case would be so I haven't done either of those things in this PR.

### CODE REVIEW

**Comment by robbert-vdh** [comment]
I noticed while this does work great in most situations, if the allocation is triggered by simpelog (and presumably some other loggers) then this will stall, presumably because it doesn't allow concurrent logging from multiple locations.

**Comment by robbert-vdh** [comment]
I already have a branch that combines both PRs: https://github.com/robbert-vdh/rust-assert-no-alloc/tree/nih-plug

**Comment by robbert-vdh** [comment]
This is incorrect. If both the backtrace and log feature are enabled then the backtrace will still always be printed to STDERR.

**Comment by Windfisch** [comment]
I see, fixed...

Can you add some words to the README describing the new features?

**Pull request merged**
